// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmZ5BkDbAHjxcq1stgZWU9QIVDIVoF42Y',
    appId: '1:415944084439:web:246573543167753702d992',
    messagingSenderId: '415944084439',
    projectId: 'hajj-6716e',
    authDomain: 'hajj-6716e.firebaseapp.com',
    storageBucket: 'hajj-6716e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP2By1RR0_GiGDU-de1T1uRZr-2DTxomg',
    appId: '1:415944084439:android:fab447bf8bd0fe7502d992',
    messagingSenderId: '415944084439',
    projectId: 'hajj-6716e',
    storageBucket: 'hajj-6716e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPLefG27f1IPrIY2oDXQlzLpfWJiNnWUM',
    appId: '1:415944084439:ios:9739402cddca60b002d992',
    messagingSenderId: '415944084439',
    projectId: 'hajj-6716e',
    storageBucket: 'hajj-6716e.firebasestorage.app',
    iosBundleId: 'com.example.hajj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPLefG27f1IPrIY2oDXQlzLpfWJiNnWUM',
    appId: '1:415944084439:ios:9739402cddca60b002d992',
    messagingSenderId: '415944084439',
    projectId: 'hajj-6716e',
    storageBucket: 'hajj-6716e.firebasestorage.app',
    iosBundleId: 'com.example.hajj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmZ5BkDbAHjxcq1stgZWU9QIVDIVoF42Y',
    appId: '1:415944084439:web:d1e816e42bcb90d602d992',
    messagingSenderId: '415944084439',
    projectId: 'hajj-6716e',
    authDomain: 'hajj-6716e.firebaseapp.com',
    storageBucket: 'hajj-6716e.firebasestorage.app',
  );
}
